In [113]:
#creating a dictionary.

#trying to interate over the node attributes to add a new color that holds the color.
#this added the value "grey" as value to all nodes.
for gender in Gnew.nodes(data=True): 
    if gender in Gnew.nodes("Gender") == "['Male']": 
        gender = "red"
        nx.set_node_attributes(Gnew, gender, "Gender_color"),
    elif gender in Gnew.nodes("Gender") == "['Female']": 
        gender = "green"
        nx.set_node_attributes(Gnew, gender, "Gender_color"),
    else: 
        gender = "grey"
        nx.set_node_attributes(Gnew, gender, "Gender_color")
#Gnew.nodes(data=True)

In [114]:
#trying to interate over the node attributes to add a new color that holds the color.
#this added the value "grey" as value to all nodes.
for gender in Gnew.nodes(data=True): 
    if gender in nx.get_node_attributes(Gnew, "Gender") == "['Male']": 
        gender = "red"
        nx.set_node_attributes(Gnew, gender, "Gender_color"),
    elif gender in nx.get_node_attributes(Gnew, "Gender") == "['Female']": 
        gender = "green"
        nx.set_node_attributes(Gnew, gender, "Gender_color"),
    else: 
        gender = "grey"
        nx.set_node_attributes(Gnew, gender, "Gender_color")
Gnew.nodes(data=True)

TypeError: unhashable type: 'dict'

In [91]:
#adding the diplay name as node attribute
#artists_name=artists_complete[["ConstituentID_unique", "DisplayName"]]
#artists_name_dic = artists_name.set_index("ConstituentID_unique").T.to_dict("list")
#adding the data to the nodes
#nx.set_node_attributes(Gnew, artists_name_dic, "DisplayName")

In [92]:
#Gnew.nodes(data=True)

In [93]:
#getting the unique values of the gender column: 
gender = single_Artistextended["Gender"].unique()
print("Gender is described with the following values:", gender)

Gender is described with the following values: [nan 'Male' 'Female']

In [94]:
#Gnew.nodes(data=True)
genderIndex = nx.get_node_attributes(Gnew,'Gender')

Not sure why this does not work. different approaches where tried.

In [95]:
#plotting the node colors based on the gender of the artist. 
#https://stackoverflow.com/questions/28910766/python-networkx-set-node-color-automatically-based-on-number-of-attribute-opt

node_color_gender = []

#for each node in the graph
for node in Gnew.nodes(data=True): 
    #if the node has the attribute "(male)":  
    if "['Male']" in node[1]:
        node_color_gender.append("green")
    #if the node has the attribute "("female"): 
    elif "['Female']" in node[1]:
        node_color_gender.append("blue")
    #if the node has the attribute "NAN":
    elif "[nan]" in node[1]:
        node_color_gender.append("grey")

node_color_gender
#I don't receive error, but node_color_gender stays empty.

[]

In [96]:
node_color_gender = []

#for each node in the graph
for node in Gnew.nodes(data=True): 
    #if the node has the attribute "(male)":  
    if "'Male'" in node[1]["Gender"]:
        node_color_gender.append("green")
    #if the node has the attribute "("female"): 
    elif "'Female'" in node[1]["Gender"]:
        node_color_gender.append("red")
    #if the node has the attribute "NAN":
    elif 'nan' in node[1]["Gender"]:
        node_color_gender.append("grey")
        
#I receive Keyerror: "Gender"

KeyError: 'Gender'

In [ ]:
node_color_gender = []
for node in Gnew.nodes(data=True):

    # if the node has the attribute group1
    if "'Male'" in node[2]['Gender']:
        node_color_gender.append('blue')

    # if the node has the attribute group1
    elif "'Female'" in node[2]['Gender']:
        node_color_gender.append('red')

    # if the node has the attribute group1
    elif 'Nan' in node[2]['Gender']:
        node_color_gender.append('green')

print(node_color_gender)

In [127]:
#trying to append the gender_color for each gender
for gen in artists_complete["Gender"]: 
    if gen == "male":
        artists_complete["gender_color"] = "blue"
        #artists_complete.append({gender_color: "blue"})
    elif gen == "female":
        artists_complete["gender_color"] = "green"
        #artists_complete.append({"gender_color": "green"})
    elif gen == "non-binary": 
        artists_complete["gender_color"] = "orange"
        #artists_complete.append({"gender_color": "orange"})
    elif gen == "Nan": 
        artists_complete["gender_color"] = "gray"
       # artists_complete.append({"gender_color": "blue"})

artists_complete

,ConstituentID,DisplayName,ArtistBio,Nationality,Gender,BeginDate,EndDate,Wiki QID,ULAN,ConstituentID_unique,gender_color
0,1,Robert Arneson,"American, 1930–1992",American,male,1930,1992,NaN,NaN,artist1,blue
1,2,Doroteo Arnaiz,"Spanish, born 1936",Spanish,male,1936,0,NaN,NaN,artist2,blue
2,3,Bill Arnold,"American, born 1941",American,male,1941,0,NaN,NaN,artist3,blue
3,4,Charles Arnoldi,"American, born 1946",American,male,1946,0,Q1063584,500027998.0,artist4,blue
4,5,Per Arnoldi,"Danish, born 1941",Danish,male,1941,0,NaN,NaN,artist5,blue
...,...,...,...,...,...,...,...,...,...,...,...
15217,133006,Andrew Chesnutt,"American, 1861–1934",American,male,1861,1934,NaN,NaN,artist133006,blue
15218,133007,Lewis Chesnutt,"American, 1860–1933",American,male,1860,1933,NaN,NaN,artist133007,blue
15219,133026,Alfred Tritschler,"German, 1905 – 1970",German,NaN,1905,1970,NaN,NaN,artist133026,blue
15220,133027,Studio of Dr. Paul Wolff & Tritschler,NaN,NaN,NaN,0,0,NaN,NaN,artist133027,blue
15221,133038,"Hamburgrer Frobelspiel-Handlung, Herm. Evers",NaN,NaN,NaN,0,0,NaN,NaN,artist133038,blue

In [132]:
#trying to append the gender_color for each gender
for lab, row in artists_complete.iterrows(): 
    if artists_complete["Gender"] == "male":
        artists_complete.loc[lab, "GenderColor"] = row["blue"]
        #artists_complete["gender_color"] = "blue"
        #artists_complete.append({gender_color: "blue"})
    elif artists_complete["Gender"] == "female":
        artists_complete.loc[lab, "GenderColor"] = row["green"]
        #artists_complete["gender_color"] = "green"
        #artists_complete.append({"gender_color": "green"})
    elif artists_complete["Gender"] == "non-binary":
        artists_complete.loc[lab, "GenderColor"] = row["orange"]
        #artists_complete["gender_color"] = "orange"
        #artists_complete.append({"gender_color": "orange"})
    elif artists_complete["Gender"] == "NaN": 
        artists_complete.loc[lab, "GenderColor"] = row["gray"]
        #artists_complete["gender_color"] = "gray"
       #artists_complete.append({"gender_color": "blue"})

artists_complete

ValueError: can only convert an array of size 1 to a Python scalar

In [137]:
#new apprach with np.where() funkction: 
#np.where(condition, value if condition is true, value if condition is false)
import numpy as np
artists_complete["Gendercolors"] = np.where(artists_complete["Gender"] == "male", "blue", "none")
artists_complete["Gendercolors"] = np.where(artists_complete["Gender"] == "feamle", "green", "none")
artists_complete["Gendercolors"] = np.where(artists_complete["Gender"] == "non-binary", "orange", "none")
artists_complete
#works with one line, but not with multiple

,ConstituentID,DisplayName,ArtistBio,Nationality,Gender,BeginDate,EndDate,Wiki QID,ULAN,ConstituentID_unique,gender_color,Gendercolors
0,1,Robert Arneson,"American, 1930–1992",American,male,1930,1992,NaN,NaN,artist1,blue,none
1,2,Doroteo Arnaiz,"Spanish, born 1936",Spanish,male,1936,0,NaN,NaN,artist2,blue,none
2,3,Bill Arnold,"American, born 1941",American,male,1941,0,NaN,NaN,artist3,blue,none
3,4,Charles Arnoldi,"American, born 1946",American,male,1946,0,Q1063584,500027998.0,artist4,blue,none
4,5,Per Arnoldi,"Danish, born 1941",Danish,male,1941,0,NaN,NaN,artist5,blue,none
...,...,...,...,...,...,...,...,...,...,...,...,...
15217,133006,Andrew Chesnutt,"American, 1861–1934",American,male,1861,1934,NaN,NaN,artist133006,blue,none
15218,133007,Lewis Chesnutt,"American, 1860–1933",American,male,1860,1933,NaN,NaN,artist133007,blue,none
15219,133026,Alfred Tritschler,"German, 1905 – 1970",German,NaN,1905,1970,NaN,NaN,artist133026,blue,none
15220,133027,Studio of Dr. Paul Wolff & Tritschler,NaN,NaN,NaN,0,0,NaN,NaN,artist133027,blue,none
15221,133038,"Hamburgrer Frobelspiel-Handlung, Herm. Evers",NaN,NaN,NaN,0,0,NaN,NaN,artist133038,blue,none

In [155]:
artists_complete.loc[artists_complete["Gender"] == "Nan"]
artists_complete = artists_complete.drop("gender_color", 1)
artists_complete = artists_complete.drop("Gendercolors", 1)

/var/folders/34/sw2csfvn5p534d16zdzqdqk40000gn/T/ipykernel_860/348515624.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  artists_complete = artists_complete.drop("gender_color", 1)
/var/folders/34/sw2csfvn5p534d16zdzqdqk40000gn/T/ipykernel_860/348515624.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  artists_complete = artists_complete.drop("Gendercolors", 1)

In [156]:
artists_complete.head()

,ConstituentID,DisplayName,ArtistBio,Nationality,Gender,BeginDate,EndDate,Wiki QID,ULAN,ConstituentID_unique,genderColour
0,1,Robert Arneson,"American, 1930–1992",American,male,1930,1992,NaN,NaN,artist1,green
1,2,Doroteo Arnaiz,"Spanish, born 1936",Spanish,male,1936,0,NaN,NaN,artist2,green
2,3,Bill Arnold,"American, born 1941",American,male,1941,0,NaN,NaN,artist3,green
3,4,Charles Arnoldi,"American, born 1946",American,male,1946,0,Q1063584,500027998.0,artist4,green
4,5,Per Arnoldi,"Danish, born 1941",Danish,male,1941,0,NaN,NaN,artist5,green

In [122]:
#I add the color to the dataframe and than add it to the graph object
chosen = ['aliceblue', 'yellow', 'green' 
          'coral']

colors = dict(zip(artists_complete['Gender'].unique(),chosen))
df_colors = pd.DataFrame({'gender_color':artists_complete['Gender'].unique(), 'colors':chosen})
df_colors.head(15)

ValueError: All arrays must be of the same length